// <auto-generated />
using System;
using CoffeeManagementSystem.Data.EntityContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CoffeeManagementSystem.Data.Migrations
{
    [DbContext(typeof(CoffeeManagementSystemContext))]
    [Migration("20210622170246_UpdateEntities")]
    partial class UpdateEntities
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CoffeeManagementSystem.Model.EntitiesModel.AttributeEntities", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AttributeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CreateBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UpdateBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Attribute");
                });

            modelBuilder.Entity("CoffeeManagementSystem.Model.EntitiesModel.AttributeValueBillDetailEntities", b =>
                {
                    b.Property<int>("BillDetailId")
                        .HasColumnType("int");

                    b.Property<int>("AttributeValueId")
                        .HasColumnType("int");

                    b.Property<int>("CreateBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UpdateBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("BillDetailId", "AttributeValueId");

                    b.ToTable("AttributeValueBillDetail");
                });

            modelBuilder.Entity("CoffeeManagementSystem.Model.EntitiesModel.AttributeValueEntities", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AttributeId")
                        .HasColumnType("int");

                    b.Property<int>("CreateBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UpdateBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AttributeValue");
                });

            modelBuilder.Entity("CoffeeManagementSystem.Model.EntitiesModel.BranchEntities", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BranchName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CreateBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ManagerEmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("NumberPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UpdateBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Branch");
                });

            modelBuilder.Entity("CoffeeManagementSystem.Model.EntitiesModel.CartEntities", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreateBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UpdateBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Cart");
                });

            modelBuilder.Entity("CoffeeManagementSystem.Model.EntitiesModel.CartItemEntities", b =>
                {
                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("CreateBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UpdateBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("CartId", "ProductId");

                    b.ToTable("CartItem");
                });

            modelBuilder.Entity("CoffeeManagementSystem.Model.EntitiesModel.CategoryEntities", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CreateBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PublicIdImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UpdateBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UrlImageCategory")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "Đá xay ",
                            CreateBy = 1,
                            CreateDate = new DateTime(2020, 12, 23, 1, 18, 30, 999, DateTimeKind.Unspecified),
                            PublicIdImage = "mka6z4skydw4ooqhspt5",
                            Status = 1,
                            UpdateBy = 1,
                            UpdateDate = new DateTime(2020, 12, 23, 1, 18, 30, 999, DateTimeKind.Unspecified),
                            UrlImageCategory = "https://res.cloudinary.com/nqcuong720/image/upload/v1623774698/mka6z4skydw4ooqhspt5.jpg"
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "Chocolate",
                            CreateBy = 1,
                            CreateDate = new DateTime(2020, 12, 23, 1, 18, 30, 999, DateTimeKind.Unspecified),
                            PublicIdImage = "mka6z4skydw4ooqhspt5",
                            Status = 1,
                            UpdateBy = 1,
                            UpdateDate = new DateTime(2020, 12, 23, 1, 18, 30, 999, DateTimeKind.Unspecified),
                            UrlImageCategory = "https://res.cloudinary.com/nqcuong720/image/upload/v1623774698/mka6z4skydw4ooqhspt5.jpg"
                        },
                        new
                        {
                            Id = 3,
                            CategoryName = "Matcha",
                            CreateBy = 1,
                            CreateDate = new DateTime(2020, 12, 23, 1, 18, 30, 999, DateTimeKind.Unspecified),
                            PublicIdImage = "mka6z4skydw4ooqhspt5",
                            Status = 1,
                            UpdateBy = 1,
                            UpdateDate = new DateTime(2020, 12, 23, 1, 18, 30, 999, DateTimeKind.Unspecified),
                            UrlImageCategory = "https://res.cloudinary.com/nqcuong720/image/upload/v1623774698/mka6z4skydw4ooqhspt5.jpg"
                        },
                        new
                        {
                            Id = 4,
                            CategoryName = "Trà Trái Cây",
                            CreateBy = 1,
                            CreateDate = new DateTime(2020, 12, 23, 1, 18, 30, 999, DateTimeKind.Unspecified),
                            PublicIdImage = "mka6z4skydw4ooqhspt5",
                            Status = 1,
                            UpdateBy = 1,
                            UpdateDate = new DateTime(2020, 12, 23, 1, 18, 30, 999, DateTimeKind.Unspecified),
                            UrlImageCategory = "https://res.cloudinary.com/nqcuong720/image/upload/v1623774698/mka6z4skydw4ooqhspt5.jpg"
                        },
                        new
                        {
                            Id = 5,
                            CategoryName = "Trà Sữa",
                            CreateBy = 1,
                            CreateDate = new DateTime(2020, 12, 23, 1, 18, 30, 999, DateTimeKind.Unspecified),
                            PublicIdImage = "mka6z4skydw4ooqhspt5",
                            Status = 1,
                            UpdateBy = 1,
                            UpdateDate = new DateTime(2020, 12, 23, 1, 18, 30, 999, DateTimeKind.Unspecified),
                            UrlImageCategory = "https://res.cloudinary.com/nqcuong720/image/upload/v1623774698/mka6z4skydw4ooqhspt5.jpg"
                        },
                        new
                        {
                            Id = 7,
                            CategoryName = "Cafe",
                            CreateBy = 1,
                            CreateDate = new DateTime(2020, 12, 23, 1, 18, 30, 999, DateTimeKind.Unspecified),
                            PublicIdImage = "mka6z4skydw4ooqhspt5",
                            Status = 1,
                            UpdateBy = 1,
                            UpdateDate = new DateTime(2020, 12, 23, 1, 18, 30, 999, DateTimeKind.Unspecified),
                            UrlImageCategory = "https://res.cloudinary.com/nqcuong720/image/upload/v1623774698/mka6z4skydw4ooqhspt5.jpg"
                        },
                        new
                        {
                            Id = 8,
                            CategoryName = "Sinh tố",
                            CreateBy = 1,
                            CreateDate = new DateTime(2020, 12, 23, 1, 18, 30, 999, DateTimeKind.Unspecified),
                            PublicIdImage = "mka6z4skydw4ooqhspt5",
                            Status = 1,
                            UpdateBy = 1,
                            UpdateDate = new DateTime(2020, 12, 23, 1, 18, 30, 999, DateTimeKind.Unspecified),
                            UrlImageCategory = "https://res.cloudinary.com/nqcuong720/image/upload/v1623774698/mka6z4skydw4ooqhspt5.jpg"
                        });
                });

            modelBuilder.Entity("CoffeeManagementSystem.Model.EntitiesModel.CredentialUserEntities", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreateBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("GroupUserId")
                        .HasColumnType("int");

                    b.Property<int>("RolesId")
                        .HasColumnType("int");

                    b.Property<string>("RolesName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UpdateBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("CredentialUser");
                });

            modelBuilder.Entity("CoffeeManagementSystem.Model.EntitiesModel.GroupUserEntities", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreateBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("GroupUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UpdateBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("GroupUser");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateBy = 1,
                            CreateDate = new DateTime(2020, 12, 23, 1, 18, 30, 999, DateTimeKind.Unspecified),
                            GroupUserName = "Admin System",
                            Status = 1,
                            UpdateBy = 1,
                            UpdateDate = new DateTime(2020, 12, 23, 1, 18, 30, 999, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CreateBy = 1,
                            CreateDate = new DateTime(2020, 12, 23, 1, 18, 30, 999, DateTimeKind.Unspecified),
                            GroupUserName = "Manager",
                            Status = 1,
                            UpdateBy = 1,
                            UpdateDate = new DateTime(2020, 12, 23, 1, 18, 30, 999, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            CreateBy = 1,
                            CreateDate = new DateTime(2020, 12, 23, 1, 18, 30, 999, DateTimeKind.Unspecified),
                            GroupUserName = "Staff",
                            Status = 1,
                            UpdateBy = 1,
                            UpdateDate = new DateTime(2020, 12, 23, 1, 18, 30, 999, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            CreateBy = 1,
                            CreateDate = new DateTime(2020, 12, 23, 1, 18, 30, 999, DateTimeKind.Unspecified),
                            GroupUserName = "Customer",
                            Status = 1,
                            UpdateBy = 1,
                            UpdateDate = new DateTime(2020, 12, 23, 1, 18, 30, 999, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("CoffeeManagementSystem.Model.EntitiesModel.ImageProductEntities", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreateBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("PublicId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UpdateBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UrlImage")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ImageProduct");
                });

            modelBuilder.Entity("CoffeeManagementSystem.Model.EntitiesModel.OrderDetailEntities", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("CreateBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Discount")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ProductPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalMoney")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UpdateBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ProductId", "OrderId");

                    b.ToTable("OrderDetail");
                });

            modelBuilder.Entity("CoffeeManagementSystem.Model.EntitiesModel.OrderEntities", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<int>("CreateBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("DeliveryMethod")
                        .HasColumnType("int");

                    b.Property<int>("Discount")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UpdateBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("CoffeeManagementSystem.Model.EntitiesModel.PositionEntities", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreateBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PositionName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UpdateBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Position");
                });

            modelBuilder.Entity("CoffeeManagementSystem.Model.EntitiesModel.ProductEntities", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("CreateBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ProductPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PublicId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UpdateBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("CoffeeManagementSystem.Model.EntitiesModel.RoleEntities", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreateBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RoleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UpdateBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateBy = 1,
                            CreateDate = new DateTime(2020, 12, 23, 1, 18, 30, 999, DateTimeKind.Unspecified),
                            RoleName = "Add Category",
                            Status = 1,
                            UpdateBy = 1,
                            UpdateDate = new DateTime(2020, 12, 23, 1, 18, 30, 999, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CreateBy = 1,
                            CreateDate = new DateTime(2020, 12, 23, 1, 18, 30, 999, DateTimeKind.Unspecified),
                            RoleName = "View Detail Category",
                            Status = 1,
                            UpdateBy = 1,
                            UpdateDate = new DateTime(2020, 12, 23, 1, 18, 30, 999, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            CreateBy = 1,
                            CreateDate = new DateTime(2020, 12, 23, 1, 18, 30, 999, DateTimeKind.Unspecified),
                            RoleName = "Update Category",
                            Status = 1,
                            UpdateBy = 1,
                            UpdateDate = new DateTime(2020, 12, 23, 1, 18, 30, 999, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            CreateBy = 1,
                            CreateDate = new DateTime(2020, 12, 23, 1, 18, 30, 999, DateTimeKind.Unspecified),
                            RoleName = "Update Status Category",
                            Status = 1,
                            UpdateBy = 1,
                            UpdateDate = new DateTime(2020, 12, 23, 1, 18, 30, 999, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            CreateBy = 1,
                            CreateDate = new DateTime(2020, 12, 23, 1, 18, 30, 999, DateTimeKind.Unspecified),
                            RoleName = "General List Category",
                            Status = 1,
                            UpdateBy = 1,
                            UpdateDate = new DateTime(2020, 12, 23, 1, 18, 30, 999, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("CoffeeManagementSystem.Model.EntitiesModel.SlideEntities", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreateBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PublicId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SlideName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UpdateBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UrlSlideImage")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Slide");
                });

            modelBuilder.Entity("CoffeeManagementSystem.Model.EntitiesModel.UserEntities", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AvartarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BirthDay")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreateBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GroupUser")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumberPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PublicId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UpdateBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "351A Lạc Long Quân Phường 5 Quận 11 TP.Hồ Chí Minh",
                            BirthDay = new DateTime(2020, 12, 23, 1, 18, 30, 999, DateTimeKind.Unspecified),
                            CreateBy = 1,
                            CreateDate = new DateTime(2020, 12, 23, 1, 18, 30, 999, DateTimeKind.Unspecified),
                            Email = "nqcuong720@gmail.com",
                            FirstName = "Cường",
                            GroupUser = 1,
                            LastName = "Nguyễn",
                            NumberPhone = "0377077630",
                            Password = "d57587b0f5bbb0c3fe9d8cb16e97b0fe",
                            Sex = "Nam",
                            Status = 1,
                            UpdateBy = 1,
                            UpdateDate = new DateTime(2020, 12, 23, 1, 18, 30, 999, DateTimeKind.Unspecified),
                            UserName = "nqcuong20"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Phường Lê Hồng Phong TP.Quảng Ngãi",
                            BirthDay = new DateTime(2020, 12, 23, 1, 18, 30, 999, DateTimeKind.Unspecified),
                            CreateBy = 1,
                            CreateDate = new DateTime(2020, 12, 23, 1, 18, 30, 999, DateTimeKind.Unspecified),
                            Email = "volengocdiep2000@gmail.com",
                            FirstName = "Diệp",
                            GroupUser = 2,
                            LastName = "Võ",
                            NumberPhone = "035458331",
                            Password = "d57587b0f5bbb0c3fe9d8cb16e97b0fe",
                            Sex = "Nữ",
                            Status = 1,
                            UpdateBy = 1,
                            UpdateDate = new DateTime(2020, 12, 23, 1, 18, 30, 999, DateTimeKind.Unspecified),
                            UserName = "vlndiep20"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
